### ISSUE TITLE
Organ Short Octave in mididings

### ISSUE THREAD

**Issue by xerostomus** [dsacre/mididings#30]
Dear Sirs, 
Before I try to program it myself, I ask if someone has not done it already.

Old organs have so called short octave:
https://en.wikipedia.org/wiki/Short_octave

In the deepest octave:
if you press E it plays C, Similarly: 
F# - > D
G# -> E 
the rest keys and notes remains the same
notes C#, D#, F#, G# are simply missing.
I need a mididings script to practice on this crazy keyboard before I go to real organ with a short octave.
Up to now I have this:
>> [ ~KeyFilter(notes=['c1', 'c#1', 'd1', 'd#1','e1', 'f#1', 'g#1']), KeyFilter(notes=['e1', 'f#1', 'g#1']) >> Transpose(-4)] >>
May be you have something smarter.

Thanks 
Xerostomus

**Comment by xerostomus** [comment]
I inserted it in a scene:
76:	Scene("organ with short octave; Ocarina 4 plus Oboe 8",
		  [ ~KeyFilter(notes=['c1', 'c#1', 'd1', 'd#1', 'f#1', 'g#1','e1']), KeyFilter(notes=['e1', 'f#1', 'g#1']) >> Transpose(-4) ] >> Transpose(0) >> [Channel(2)>> Transpose(12) ,Channel(3)],
		  [ Ctrl(1, 2, 91, 125), # big reverb
                    Ctrl(1, 2, 1, 0) >> Ctrl(1, 2, 32, 0) >> Program(1,  2,  80), # Ocarine
                    Ctrl(1, 3, 1, 0) >> Ctrl(1, 3, 32, 0) >> Program(1,  3,  69)  # Oboe
                    #Ctrl(1, 3, 1, MSB) >> Ctrl(1, 3, 32, LSB) >> Program(1,  3,  number_intrument)  # set a bank and most significant byte MSB and least significant byte LSB  along with a program change.
		  ]
             ), 
So I can practice at home... :-)

**Comment by stefets** [comment]
Interesting, you have the right recipe.

However, this is not a problem/issue with the mididings software. You should mark the problem as solved, please.

For help you can ask your questions on this forum https://groups.google.com/forum/#!forum/mididings

**Comment by xerostomus** [comment]
Sorry I am new to Github. 
But any way thanks all the authors for mididings. 
More examples are needed for beginners as I am.
:-)

**Comment by stefets** [comment]
No problems xerostomus!

If you want examples you can check the WIKI here :  https://github.com/dsacre/mididings/wiki
You can take a look at mine here : https://github.com/stefets/live-config it's huge
