### ISSUE TITLE
Not run on python 2.7

### ISSUE THREAD

**Issue by xerostomus** [dsacre/mididings#31]
I have a fresh instalation of mididings:
$python --version
Python 2.7.15rc1

$ mididings
Traceback (most recent call last):
  File "/usr/bin/mididings", line 18, in <module>
    import mididings
  File "/usr/lib/python2.7/dist-packages/mididings/__init__.py", line 13, in <module>
    from mididings.setup import config, hook
  File "/usr/lib/python2.7/dist-packages/mididings/setup.py", line 13, in <module>
    import _mididings
ImportError: dynamic module does not define init function (init_mididings)

I have no idea how to get rid of this error.

In the last time I have feeling that Linux is corrupted a lot these days.  :-((

**Comment by stefets** [comment]
That's strange, what is you OS version ? mididings version ?

On my side that setup works fine on ubuntu mate 16.04 and a Raspberry PI 2

mididings --version
**mididings 2015+rbbec99a, using Python 2.7.12**

python --version
**Python 2.7.12**

uname -a
**Linux rpi2 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux**

**Comment by xerostomus** [comment]
Dear Mr. Gagnon,
thanks for you care.
I do not program much and not in Python, so I am pretty lost.

a) I have a fresh installation of mididings and it does not run on my Lenovo T430

b) mididings runs on my Raspberry PI  (some pictures are here: http://klimes.wz.cz/noty/mididings/)

C) I tried to find some special lines in setup.py but they werent there.
see https://github.com/dsacre/mididings/commit/3b2f7d3813a4d43b9ad8f226fb71db2d6538db19

d) technical details

I have:
Lenovo T430

uname -arv
Linux T430 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

mididings -version
Traceback (most recent call last):
  File "/usr/bin/mididings", line 18, in <module>
    import mididings
  File "/usr/lib/python2.7/dist-packages/mididings/__init__.py", line 13, in <module>
    from mididings.setup import config, hook
  File "/usr/lib/python2.7/dist-packages/mididings/setup.py", line 13, in <module>
    import _mididings
ImportError: dynamic module does not define init function (init_mididings)

python --version
Python 2.7.15rc1

/usr/lib/python2.7/dist-packages/mididings$ ls -r -l 
-rw-r--r-- 1 root root 12283 pro 31 11:05 util.pyc
-rw-r--r-- 1 root root  9773 dub  8  2012 util.py
-rw-r--r-- 1 root root  3122 pro 31 11:05 unitrepr.pyc
-rw-r--r-- 1 root root  2309 dub  8  2012 unitrepr.py
-rw-r--r-- 1 root root  3867 dub 20  2012 setup.py.jerom
-rw-r--r-- 1 root root  4178 pro 31 11:05 setup.pyc
-rw-r--r-- 1 root root  3867 dub 20  2012 setup.py
-rw-r--r-- 1 root root  1701 pro 31 11:05 scene.pyc
-rw-r--r-- 1 root root  1368 dub  6  2012 scene.py
-rw-r--r-- 1 root root  2740 pro 31 11:05 patch.pyc
-rw-r--r-- 1 root root  2236 dub  2  2012 patch.py
-rw-r--r-- 1 root root  4764 pro 31 11:05 overload.pyc
-rw-r--r-- 1 root root  4280 dub  8  2012 overload.py
-rw-r--r-- 1 root root  7776 pro 31 11:05 misc.pyc
-rw-r--r-- 1 root root  4348 dub  8  2012 misc.py
-rw-r--r-- 1 root root   573 pro 31 11:05 __init__.pyc
-rw-r--r-- 1 root root   642 dub 19  2012 __init__.py
-rw-r--r-- 1 root root 14909 pro 31 11:05 event.pyc
-rw-r--r-- 1 root root 10491 dub  6  2012 event.py
-rw-r--r-- 1 root root 12057 pro 31 11:05 engine.pyc
-rw-r--r-- 1 root root 10526 dub 13  2012 engine.py
-rw-r--r-- 1 root root  1152 pro 31 11:05 constants.pyc
-rw-r--r-- 1 root root  1398 dub  5  2012 constants.py
-rw-r--r-- 1 root root 19751 pro 31 11:05 arguments.pyc
-rw-r--r-- 1 root root 13330 dub  8  2012 arguments.py

units:
insgesamt 124
-rw-r--r-- 1 root root  5313 pro 31 11:05 splits.pyc
-rw-r--r-- 1 root root  3430 dub  7  2012 splits.py
-rw-r--r-- 1 root root  4224 pro 31 11:05 printing.pyc
-rw-r--r-- 1 root root  3537 dub  7  2012 printing.py
-rw-r--r-- 1 root root  9497 pro 31 11:05 modifiers.pyc
-rw-r--r-- 1 root root  7140 dub  8  2012 modifiers.py
-rw-r--r-- 1 root root  3224 pro 31 11:05 init.pyc
-rw-r--r-- 1 root root   633 pro 31 11:05 __init__.pyc
-rw-r--r-- 1 root root  2335 dub  5  2012 init.py
-rw-r--r-- 1 root root   770 dub  1  2012 __init__.py
-rw-r--r-- 1 root root  3782 pro 31 11:05 generators.pyc
-rw-r--r-- 1 root root  3800 dub  8  2012 generators.py
-rw-r--r-- 1 root root  5718 pro 31 11:05 filters.pyc
-rw-r--r-- 1 root root  3979 dub  1  2012 filters.py
-rw-r--r-- 1 root root  1803 pro 31 11:05 engine.pyc
-rw-r--r-- 1 root root  1282 dub  8  2012 engine.py
-rw-r--r-- 1 root root  4408 pro 31 11:05 call.pyc
-rw-r--r-- 1 root root  2995 dub  7  2012 call.py
-rw-r--r-- 1 root root 12829 pro 31 11:05 base.pyc
-rw-r--r-- 1 root root  6783 dub  7  2012 base.py

live:
insgesamt 48
-rw-r--r-- 1 root root 4758 pro 31 11:05 widgets.pyc
-rw-r--r-- 1 root root 3258 dub 23  2012 widgets.py
-rw-r--r-- 1 root root 3943 pro 31 11:05 osc_control.pyc
-rw-r--r-- 1 root root 2112 dub 23  2012 osc_control.py
-rw-r--r-- 1 root root 9737 pro 31 11:05 livedings.pyc
-rw-r--r-- 1 root root 9404 dub  5  2012 livedings.py
-rw-r--r-- 1 root root  146 pro 31 11:05 __init__.pyc
-rw-r--r-- 1 root root    0 úno 23  2010 __init__.py

extra:
insgesamt 144
-rw-r--r-- 1 root root 3194 pro 31 11:05 voices.pyc
-rw-r--r-- 1 root root 3926 dub  5  2012 voices.py
-rw-r--r-- 1 root root 1140 pro 31 11:05 suppress_pc.pyc
-rw-r--r-- 1 root root  750 dub 23  2012 suppress_pc.py
-rw-r--r-- 1 root root 3056 pro 31 11:05 polyphony.pyc
-rw-r--r-- 1 root root 3089 dub 23  2012 polyphony.py
-rw-r--r-- 1 root root  873 pro 31 11:05 per_channel.pyc
-rw-r--r-- 1 root root  669 dub 23  2012 per_channel.py
-rw-r--r-- 1 root root 3105 pro 31 11:05 pedal_noteoff.pyc
-rw-r--r-- 1 root root 2896 dub 23  2012 pedal_noteoff.py
-rw-r--r-- 1 root root 1329 pro 31 11:05 panic.pyc
-rw-r--r-- 1 root root 1155 dub 23  2012 panic.py
-rw-r--r-- 1 root root 6823 pro 31 11:05 osc.pyc
-rw-r--r-- 1 root root 4466 dub  5  2012 osc.py
-rw-r--r-- 1 root root 1669 pro 31 11:05 memorize_scene.pyc
-rw-r--r-- 1 root root 1470 bře 20  2012 memorize_scene.py
-rw-r--r-- 1 root root 1956 pro 31 11:05 latch.pyc
-rw-r--r-- 1 root root 1835 dub  5  2012 latch.py
-rw-r--r-- 1 root root  688 pro 31 11:05 key_color.pyc
-rw-r--r-- 1 root root  702 dub 23  2012 key_color.py
-rw-r--r-- 1 root root 2059 pro 31 11:05 inotify.pyc
-rw-r--r-- 1 root root 2144 dub  7  2012 inotify.py
-rw-r--r-- 1 root root  787 pro 31 11:05 __init__.pyc
-rw-r--r-- 1 root root  918 dub 23  2012 __init__.py
-rw-r--r-- 1 root root 3518 pro 31 11:05 harmonizer.pyc
-rw-r--r-- 1 root root 3727 dub  5  2012 harmonizer.py
-rw-r--r-- 1 root root 3412 pro 31 11:05 gm.pyc
-rw-r--r-- 1 root root 3459 dub 23  2012 gm.py
-rw-r--r-- 1 root root 2991 pro 31 11:05 floating_split.pyc
-rw-r--r-- 1 root root 3224 dub  1  2012 floating_split.py
-rw-r--r-- 1 root root  914 pro 31 11:05 engine.pyc
-rw-r--r-- 1 root root  540 dub 23  2012 engine.py
-rw-r--r-- 1 root root 1644 pro 31 11:05 dbus.pyc
-rw-r--r-- 1 root root 1115 dub 23  2012 dbus.py

**Comment by stefets** [comment]
Hi,

The setup.py you are talking about is probably the one that reside here /usr/lib/python2.7/dist-packages/mididings ?

If fact, it's the setup.py locate here https://github.com/dsacre/mididings/blob/master/setup.py

I suggest you to uninstall mididings, clone the master branch a rebuild mididings, you will have the latest version and fixes and maybe it will work on your Lenovo !

You have the installation instructions here : http://das.nasophon.de/mididings/ at the bottom of the page

Then, 
mididings --version
Should give,
mididings 2015+rbbec99a, using Python 2.7.***
