### ISSUE TITLE
Can´t find the right start

### ISSUE THREAD

**Issue by Mickinator** [dsacre/mididings#36]
Hi everybody,
I try to find a startpoint to run mididings.
But everytime I give a command to the commandline i get a failure.
e.g.
![image](https://user-images.githubusercontent.com/55761217/73594744-74873500-4511-11ea-89b8-b2cf7b331347.png)

Is there a tested workaround, that I can go step by step?
Thanx for helping

**Comment by stefets** [comment]
Hello, it's not an issue with Mididings, you should ask to the newsgroups.
Anyway, try running with sudo may help

**Comment by Mickinator** [comment]
Hello,
yes, that's right. Where do I find the newsgroup?



Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Stéphane Gagnon <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [dsacre/mididings] Can´t find the right start (#36)
Datum: 01.02.2020, 23:26 Uhr
An: dsacre/mididings <mididings@noreply.github.com
<mailto:mididings@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Hello, it's not an issue with Mididings, you should ask to the newsgroups.
Anyway, try running with sudo may help

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dsacre/mididings/issues/36?email_source=notifications&email_token=ANJNSQLSIMYBXOU6XY32XMTRAXZKXA5CNFSM4KOTZPWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKRIF3Q#issuecomment-581075694> 
, or unsubscribe

**Comment by stefets** [comment]
Check my WIKI, you will find answers there.
[https://github.com/stefets/live-config/wiki/How-I-build-Mididings](url)
Mididings has an official site, an official documentation and official newsgroups.
You should also close this issue.
Thank you

**Comment by Mickinator** [comment]
Please, can you send me the link to the newsgroup? 
I'm not fit with guithub and I search me going crazy ....
Thanx for understanding 💐

**Comment by stefets** [comment]
Hi,
Here is the link for the newsgroup : https://groups.google.com/forum/#!forum/mididings
You need a Google Account in order to post questions.
Don't forget to close this issue !
