### ISSUE TITLE
Python 3.11 : AttributeError: module 'inspect' has no attribute 'formatargspec'.

### ISSUE THREAD

**Issue by stefets** [dsacre/mididings#42]
Need help to fix this problem 

  File "/home/stefets/src/.venv/mididings/lib/python3.11/site-packages/mididings-2015+r5ec70c1-py3.11-linux-x86_64.egg/mididings/arguments.py", line 73, in __call__
    '%s%s' % (f.__name__, inspect.formatargspec(*signature)),
                          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'formatargspec'. Did you mean: 'formatargvalues'?

**Comment by MaurizioB** [comment]
Please avoid duplicates. Consider merging either #41 or this with the other and delete it.

**Comment by stefets** [comment]
> Please avoid duplicates. Consider merging either #41 or this with the other and delete it.

This is not a duplicate;

There are 2 issues with Python 3.11;

Look closely, the description of problem #41 is different from the description of problem #42.

There is a problem with formatargspec and another with getargspec

**Comment by MaurizioB** [comment]
Did you search those errors? They **both** refer to the same aspect, as explained in the [change log of python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#removed):

> - Removed from the `inspect` module:
>   - The `getargspec()` function, deprecated since Python 3.0; use [`inspect.signature()`](https://docs.python.org/3.11/library/inspect.html#inspect.signature) or [`inspect.getfullargspec()`](https://docs.python.org/3.11/library/inspect.html#inspect.getfullargspec) instead.
> 
>   - The `formatargspec()` function, deprecated since Python 3.5; use the [`inspect.signature()`](https://docs.python.org/3.11/library/inspect.html#inspect.signature) function or the [`inspect.Signature`](https://docs.python.org/3.11/library/inspect.html#inspect.Signature) object directly.

**Comment by stefets** [comment]
Please stop with your thumbs down, I don't need your aggressive approach and your IT morality. Problems should be reported here for other users. I searched the solutions and saw the recommendations, I will try to fix the problem but I like to hear the opinion of other programmers who use mididings. But not moralizing opinions like yours.

**Comment by stefets** [comment]
I'll work on that in my fork
